# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.CharField(max_length=4)),
                ('Quarter', models.CharField(blank=True, max_length=1)),
                ('Date', models.DateField(verbose_name='Date')),
                ('Company', models.CharField(blank=True, max_length=50)),
                ('Revenues', models.DecimalField(blank=True, decimal_places=2, max_digits=19)),
                ('EBIT', models.DecimalField(blank=True, decimal_places=2, max_digits=19)),
                ('linktoAR', models.URLField(blank=True)),
                ('Comment', models.CharField(blank=True, max_length=400)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
