# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financialanalystapp', '0002_company_employees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='Employees',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
