# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financialanalystapp', '0003_auto_20160828_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='CostofSales',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=19),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='PPE',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='company',
            name='SGandA',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=19),
            preserve_default=False,
        ),
    ]
